DEFAULT_LINT_LEVEL = "warning"
DEFAULT_LINT_MAX_LINE_LENGTH = 120

LEVELS = {
    "error": 0,
    "warning": 1,
    "style": 2,
    "security": 3,
}

DEFAULT_RULES = [
    "undefined-var",
    "type-mismatch",
    "const-reassign",
    "missing-return",
    "invalid-import",
    "duplicate-param",
    "unreachable-code",
    "unused-var",
    "unused-import",
    "prefer-const",
    "no-shadow",
    "naming-convention",
    "max-line-length",
    "trailing-whitespace",
    "spacing-operators",
    "empty-lines",
    "eval-usage",
    "unsafe-import",
    "hardcoded-secret",
    "division-by-zero-risk",
    "prefer-nullable",
]

BUILTIN_SYMBOLS = {
    "append",
    "cancel",
    "clear",
    "cls",
    "eval",
    "false",
    "extend",
    "input",
    "is_array",
    "is_bool",
    "is_dict",
    "is_float",
    "is_func",
    "is_int",
    "is_list",
    "is_null",
    "is_num",
    "is_str",
    "len",
    "null",
    "output",
    "pop",
    "print",
    "println",
    "range",
    "reprint",
    "to_bool",
    "to_float",
    "to_int",
    "to_string",
    "true",
    "typeof",
}
